import Head from 'next/head';

const Headpage = () => {
    return (
        <Head>
            <title>Vietnam Luxury Tours I Wellness Vietnam I Adventure Travel & Incentive Tailor-made Trips</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/assets/images/logo.png" />
        </Head>
    )
}

export default Headpage