import Head from 'next/head';
import { Inter } from '@next/font/google';
import classNames from 'classnames/bind';
import styles from '@/styles/Home.module.scss';

// import Image from 'next/image';
import { SwiperSlide, Swiper } from 'swiper/react';

import 'swiper/css';
import 'swiper/css/effect-fade';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

import { EffectFade, Pagination, Autoplay, Navigation } from 'swiper';

import SwiperSlideComp from '@/components/SwiperSlideComp';
import { banners } from '@/styles/images';
import { Banner, ItemInfoHome } from '@/views';

import { iconInfos } from '@/styles/images';
import ICON1 from '@/styles/images/icons/iconInfo1.jpg';

const cx = classNames.bind(styles);

const inter = Inter({ subsets: ['latin'] });

console.log('iconInfos', iconInfos.icon1);

const InfoFake = [
    {
        icon: ICON1,
        title: 'excellent',
        content:
            'The tours featured throughout our website are intended to give you ideas for whats possible when you travel with us. Treat them simply as inspiration',
    },
    {
        icon: ICON1,
        title: 'excellent',
        content:
            'The tours featured throughout our website are intended to give you ideas for whats possible when you travel with us. Treat them simply as inspiration',
    },
    {
        icon: ICON1,
        title: 'excellent',
        content:
            'The tours featured throughout our website are intended to give you ideas for whats possible when you travel with us. Treat them simply as inspiration',
    },
    {
        icon: ICON1,
        title: 'excellent',
        content:
            'The tours featured throughout our website are intended to give you ideas for whats possible when you travel with us. Treat them simply as inspiration',
    },
    {
        icon: ICON1,
        title: 'excellent',
        content:
            'The tours featured throughout our website are intended to give you ideas for whats possible when you travel with us. Treat them simply as inspiration',
    },
];

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App khanh</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={cx('wrapperBanner')}>
                <SwiperSlideComp className={cx('bodyBanner')}>
                    <SwiperSlide>
                        <Banner className={cx('bannerMain')} image={banners.banner1} />
                    </SwiperSlide>
                    <SwiperSlide>
                        <Banner className={cx('bannerMain')} image={banners.banner2} />
                    </SwiperSlide>
                    <SwiperSlide>
                        <Banner className={cx('bannerMain')} image={banners.banner3} />
                    </SwiperSlide>
                    <div className={cx('sheaderBox')}></div>
                </SwiperSlideComp>

                <Swiper
                    className={cx('boxInfo')}
                    modules={[Autoplay]}
                    spaceBetween={0}
                    grabCursor={true}
                    autoplay={{
                        delay: 8000,
                        disableOnInteraction: false,
                    }}
                    loop={true}
                    breakpoints={{
                        0: {
                            slidesPerView: 1,
                        },
                        640: {
                            slidesPerView: 2,
                        },
                        768: {
                            slidesPerView: 3,
                        },
                        1024: {
                            slidesPerView: 4,
                        },
                    }}
                >
                    {InfoFake.map((item, index) => (
                        <SwiperSlide key={index}>
                            <ItemInfoHome data={item} id={index + 1} />
                        </SwiperSlide>
                    ))}
                </Swiper>
            </div>
            {/* <main className={styles.main}>
                <div className={styles.description}>
                    <p>
                        Get started by editing&nbsp;
                        <code className={styles.code}>pages/index.js</code>
                    </p>
                    <div>
                        <a
                            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            By{' '}
                            <Image
                                src="/vercel.svg"
                                alt="Vercel Logo"
                                className={styles.vercelLogo}
                                width={100}
                                height={24}
                                priority
                            />
                        </a>
                    </div>
                </div>

                <div className={styles.center}>
                    <Image
                        className={styles.logo}
                        src="/next.svg"
                        alt="Next.js Logo"
                        width={180}
                        height={37}
                        priority
                    />
                    <div className={styles.thirteen}>
                        <Image src="/thirteen.svg" alt="13" width={40} height={31} priority />
                    </div>
                </div>

                <div className={styles.grid}>
                    <a
                        href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            Docs <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Find in-depth information about Next.js features and&nbsp;API.
                        </p>
                    </a>

                    <a
                        href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            Learn <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Learn about Next.js in an interactive course with&nbsp;quizzes!
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            Templates <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Discover and deploy boilerplate example Next.js&nbsp;projects.
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            Deploy <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.
                        </p>
                    </a>
                </div> */}
            {/* </main> */}
        </>
    );
}
