import Head from 'next/head';
import { Inter } from '@next/font/google';
import classNames from 'classnames/bind';
import styles from '@/styles/Home.module.scss';
import BlogHome from '@/views/BlogHome';

// import Image from 'next/image';
import { SwiperSlide, Swiper } from 'swiper/react';

import 'swiper/css';
import 'swiper/css/effect-fade';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

import { EffectFade, Pagination, Autoplay, Navigation } from 'swiper';

import SwiperSlideComp from '@/components/SwiperSlideComp';
import { banners } from '@/public/images';
import { Banner, ItemInfoHome } from '@/views';

// import { iconInfos } from '@/public/images';
import ICON1 from '@/public/images/icons/iconInfo1.jpg';
import Country from '@/views/Country/Country';

const cx = classNames.bind(styles);

const inter = Inter({ subsets: ['latin'] });

const InfoFake = [
    {
        icon: ICON1,
        title: 'excellent',
        content:
            'The tours featured throughout our website are intended to give you ideas for whats possible when you travel with us. Treat them simply as inspiration',
    },
    {
        icon: ICON1,
        title: 'excellent',
        content:
            'The tours featured throughout our website are intended to give you ideas for whats possible when you travel with us. Treat them simply as inspiration',
    },
    {
        icon: ICON1,
        title: 'excellent',
        content:
            'The tours featured throughout our website are intended to give you ideas for whats possible when you travel with us. Treat them simply as inspiration',
    },
    {
        icon: ICON1,
        title: 'excellent',
        content:
            'The tours featured throughout our website are intended to give you ideas for whats possible when you travel with us. Treat them simply as inspiration',
    },
    {
        icon: ICON1,
        title: 'excellent',
        content:
            'The tours featured throughout our website are intended to give you ideas for whats possible when you travel with us. Treat them simply as inspiration',
    },
];

export default function Home() {
    return (
        <>
            <Head>
                <title>Vietnam DMC | Wellness | Luxury | MICE | Responsible | Packages | Indochina packages</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="./logo.png" />
            </Head>
            <div className={cx('wrapperBanner')}>
                <SwiperSlideComp className={cx('bodyBanner')}>
                    <SwiperSlide>
                        <Banner className={cx('bannerMain')} image={banners.banner1} />
                    </SwiperSlide>
                    <SwiperSlide>
                        <Banner className={cx('bannerMain')} image={banners.banner2} />
                    </SwiperSlide>
                    <SwiperSlide>
                        <Banner className={cx('bannerMain')} image={banners.banner3} />
                    </SwiperSlide>
                    <div className={cx('sheaderBox')}></div>
                </SwiperSlideComp>

                <Swiper
                    className={cx('boxInfo')}
                    modules={[Autoplay]}
                    spaceBetween={0}
                    grabCursor={true}
                    autoplay={{
                        delay: 8000,
                        disableOnInteraction: false,
                    }}
                    loop={true}
                    breakpoints={{
                        0: {
                            slidesPerView: 1,
                        },
                        640: {
                            slidesPerView: 2,
                        },
                        768: {
                            slidesPerView: 3,
                        },
                        1024: {
                            slidesPerView: 4,
                        },
                    }}
                >
                    {InfoFake.map((item, index) => (
                        <SwiperSlide key={index}>
                            <ItemInfoHome data={item} id={index + 1} />
                        </SwiperSlide>
                    ))}
                </Swiper>
                <Country />
                <BlogHome />
            </div>
        </>
    );
}
